[package]
name = "montools"
version = "0.1.1"
description = "Monitor input + KVM switching over DDC/CI"
authors = ["you"]
edition = "2021"
default-run = "montools"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "montools_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ddc-hi = { version = "0.4.1", default-features = false, features = ["ddc-i2c", "ddc-winapi", "ddc-macos"] }
tauri-plugin-global-shortcut = "2.4.0"
tauri-plugin-autostart = "2.7.0"
tauri-plugin-single-instance = "2.5.2"
dirs = "7.0.0"
anyhow = "1.0.104"


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
